---
- name: Start service
  become: false
  hosts: all
  vars:
    remote_folder: "{{ remote_folder_path }}"
    # e.g. develop
    project_stage: "{{ project_stage }}"
    # e.g. backend
    project_service: "{{ project_service }}"
    # Convert comma-separated string to list
    # Should receive something like "backend,frontend" from Jenkinsfile
    project_services: "{{ project_services.split(',') }}"

  tasks:
    - name: Setup base docker compose file
      template:
        src: ../docker/docker-compose.base.yml.j2
        dest: "{{ remote_folder }}/docker-compose.base.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Copy docker compose file to service directory
      template:
        src: ../docker/docker-compose.{{ project_service }}.yml.j2
        dest: "{{ remote_folder }}/docker-compose.{{ project_service }}.yml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
        force: true

    - name: Start service with docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ remote_folder }}"
        files: >
            {{
              project_services | map('regex_replace', '^(.*)$', 'docker-compose.\1.yml') | list +
              ['docker-compose.base.yml']
            }}
        env_files: >
            {{
              project_services | map('regex_replace', '^(.*)$', '.version.\1') | list
            }}
        wait: true
        wait_timeout: 60

